# Deployment for PandaCloud App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandacloud-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pandacloud-app
  template:
    metadata:
      labels:
        app: pandacloud-app
    spec:
      containers:
        - name: pandacloud-container
          image: 050451361261.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
# Service to expose the PandaCloud App
apiVersion: v1
kind: Service
metadata:
  name: pandacloud-service
spec:
  selector:
    app: pandacloud-app
  type: LoadBalancer
  ports:
    - name: http
      port: 5000         # Expose on port 5000 externally
      targetPort: 5000   # Container listens on 5000
